abpframework/eShopOnAbp

- apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbp.AuthServer.csproj
- etc/dev-cert/create-certificate.ps1
- etc/docker/docker-compose.infrastructure.yml
- etc/docker/down.ps1
- etc/docker/up.ps1
- gateways/internal/src/EShopOnAbp.InternalGateway/Properties/launchSettings.json
- global.json
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/EShopOnAbp.AdministrationService.EntityFrameworkCore.csproj
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/EShopOnAbp.AdministrationService.HttpApi.Host.csproj
- services/administration/test/EShopOnAbp.AdministrationService.EntityFrameworkCore.Tests/EShopOnAbp.AdministrationService.EntityFrameworkCore.Tests.csproj
- services/administration/test/EShopOnAbp.AdministrationService.EntityFrameworkCore.Tests/EntityFrameworkCore/AdministrationServiceEntityFrameworkCoreTestModule.cs
- services/administration/test/EShopOnAbp.AdministrationService.TestBase/AdministrationServiceTestBaseModule.cs
- services/identity/src/EShopOnAbp.IdentityService.EntityFrameworkCore/EShopOnAbp.IdentityService.EntityFrameworkCore.csproj
- services/saas/src/EShopOnAbp.SaasService.EntityFrameworkCore/EShopOnAbp.SaasService.EntityFrameworkCore.csproj
Fixes https://github.com/abpframework/abp/issues/10231
> EShopOnAbp: EfCore Mismatch for AuthServer and Administration Service

- apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbpAuthServerBrandingProvider.cs
- apps/auth-server/src/EShopOnAbp.AuthServer/Pages/Index.cshtml
- apps/auth-server/src/EShopOnAbp.AuthServer/Pages/Index.cshtml.cs
- apps/auth-server/src/EShopOnAbp.AuthServer/Pages/_ViewImports.cshtml
- Closes https://github.com/abpframework/abp/issues/10232
---
After this PR, AuthServer will look like:
> AuthServer - Design Improvements

- build/build-images-locally.ps1
- build/build-images.ps1
- etc/k8s/eshoponabp/charts/authserver/templates/authserver-deployment.yaml
- etc/k8s/eshoponabp/charts/authserver/values.yaml
- etc/k8s/eshoponabp/charts/postgres/Chart.yaml
- etc/k8s/eshoponabp/charts/postgres/templates/postgres-deployment.yaml
- etc/k8s/eshoponabp/charts/postgres/templates/postgres-service.yaml
- etc/k8s/eshoponabp/values.yaml
Closes https://github.com/abpframework/abp/issues/10739
> eShopOnAbp: Update helm charts for PostgreSQL

- etc/docker/docker-compose.infrastructure.override.yml
- etc/docker/docker-compose.infrastructure.yml
- etc/k8s/eshoponabp/charts/mongodb/Chart.yaml
- etc/k8s/eshoponabp/charts/mongodb/templates/mongodb-deployment.yaml
- etc/k8s/eshoponabp/charts/mongodb/templates/mongodb-service.yaml
Fixes https://github.com/abpframework/abp/issues/10977
> eShopOnAbp: add MongoDb to docker-compose

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/LoginLink/Default.cshtml
- Closes https://github.com/abpframework/abp/issues/11017
Login link is visible right now:
> Fix invisible login button

- apps/public-web/src/EShopOnAbp.PublicWeb/Basket/UserBasketProvider.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Basket/BasketWidgetViewComponent.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Basket/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Basket.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Basket.cshtml.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Payment.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Payment.cshtml.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/components/basket-widget.js
Closes https://github.com/abpframework/abp/issues/11059
> Redirect to login if user is unauthorized when purchase is clicked with same return url

- services/payment/src/EShopOnAbp.PaymentService.Application.Contracts/PaymentServiceConsts.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentRequests/PaymentRequestAppService.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentRequests/PaymentRequestByPassAppService.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentServiceApplicationModule.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/PaymentServiceHttpApiHostModule.cs
Closes https://github.com/abpframework/abp/issues/11107
> Add Payment Provider bypassing

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Payment/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/UserOrders/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/MyOrders.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/OrderReceived.cshtml
- shared/EShopOnAbp.Shared.Localization/Localization/EShopOnAbp/en.json
- shared/EShopOnAbp.Shared.Localization/Localization/EShopOnAbp/tr.json
Closes https://github.com/abpframework/abp/issues/11263
> eShopOnAbp: Fix missing localizations

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Cart/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Menus/EShopOnAbpPublicWebToolbarContributor.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/components/cart/cart-widget.css
- Closes https://github.com/abpframework/abp/issues/11178
> Cart popover

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Payment/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPaymentConsts.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Payment.cshtml.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/PaymentCompleted.cshtml.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/payment.js
- apps/public-web/src/EShopOnAbp.PublicWeb/ServiceProviders/PaymentTypeProvider.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/components/payment/payment-widget.js
- services/payment/src/EShopOnAbp.PaymentService.Application.Contracts/PaymentMethods/PaymentTypeIds.cs
- services/payment/src/EShopOnAbp.PaymentService.Application.Contracts/PaymentMethods/PaymentTypes.cs
- services/payment/src/EShopOnAbp.PaymentService.Application.Contracts/PaymentRequests/IPaymentRequestAppService.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentMethods/DemoPaymentMethod.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentMethods/IPaymentMethod.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentMethods/PaymentMethodResolver.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentMethods/PaypalMethod.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentRequests/PaymentRequestAppService.cs
- services/payment/src/EShopOnAbp.PaymentService.Application/PaymentServiceApplicationModule.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Client/ClientProxies/PaymentRequestClientProxy.Generated.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Client/ClientProxies/PaymentRequestClientProxy.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Client/ClientProxies/payment-generate-proxy.json
- services/payment/src/EShopOnAbp.PaymentService.HttpApi/Controllers/PaymentRequestController.cs
- Moved Webhook handling to PaymentMethod.
- Added PaymentType instead of PaymentId
- Updated PublicWeb project to use PeymentType instead of PaymentId
> PaymentMethod Improvements

- apps/auth-server/src/EShopOnAbp.AuthServer/appsettings.json
- gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbpWebPublicGatewayModule.cs
- gateways/web-public/src/EShopOnAbp.WebPublicGateway/appsettings.json
- gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbpWebGatewayModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/AdministrationServiceHttpApiHostModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/appsettings.json
- services/basket/src/EShopOnAbp.BasketService.HttpApi.Host/appsettings.json
- services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/appsettings.json
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/DbMigrations/IdentityServerDataSeeder.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/IdentityServiceHttpApiHostModule.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/appsettings.json
- services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/appsettings.json
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/appsettings.json
There is single swagger client now named `WebGateway_Swagger` that has allowance for all the api scopes.
Closes https://github.com/abpframework/abp/issues/11389
> eShopOnAbp: Gateway multiple api definition authorization

- apps/auth-server/src/EShopOnAbp.AuthServer/EShopOnAbpAuthServerModule.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
- gateways/web-public/src/EShopOnAbp.WebPublicGateway/EShopOnAbpWebPublicGatewayModule.cs
- gateways/web/src/EShopOnAbp.WebGateway/EShopOnAbpWebGatewayModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/AdministrationServiceHttpApiHostModule.cs
- services/basket/src/EShopOnAbp.BasketService.HttpApi.Host/BasketServiceHttpApiHostModule.cs
- services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/CatalogServiceHttpApiHostModule.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/IdentityServiceHttpApiHostModule.cs
- services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/OrderingServiceHttpApiHostModule.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/PaymentServiceHttpApiHostModule.cs
fixes step of https://github.com/abpframework/abp/issues/11448
closes https://github.com/abpframework/abp/issues/11448
> Use async initialization methods and remove AsyncHelper usages in the module classes.

- apps/angular/src/environments/environment.ts
- apps/public-web/src/EShopOnAbp.PublicWeb/ServiceProviders/UserBasketProvider.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/client-proxies/basket-proxy.js
- services/basket/src/EShopOnAbp.BasketService.Application.Contracts/IBasketAppService.cs
- services/basket/src/EShopOnAbp.BasketService.Application/BasketAppService.cs
- services/basket/src/EShopOnAbp.BasketService.Application/BasketProductService.cs
- services/basket/src/EShopOnAbp.BasketService.Domain.Shared/BasketServiceDomainErrorCodes.cs
- services/basket/src/EShopOnAbp.BasketService.Domain.Shared/Localization/BasketService/en.json
- services/basket/src/EShopOnAbp.BasketService.Domain.Shared/Localization/BasketService/tr.json
- services/basket/src/EShopOnAbp.BasketService.Domain/Basket.cs
- services/basket/src/EShopOnAbp.BasketService.HttpApi.Client/ClientProxies/BasketClientProxy.Generated.cs
- services/basket/src/EShopOnAbp.BasketService.HttpApi.Client/ClientProxies/BasketClientProxy.cs
- services/basket/src/EShopOnAbp.BasketService.HttpApi.Client/ClientProxies/basket-generate-proxy.json
- services/catalog/src/EShopOnAbp.CatalogService.Application/Products/ProductAppService.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/DbMigrations/IdentityServerDataSeeder.cs
fixes https://github.com/abpframework/abp/issues/11477
> eShopOnAbp: Refactor Basket service

- services/ordering/src/EShopOnAbp.OrderingService.Domain.Shared/Localization/OrderingService/en.json
- services/ordering/src/EShopOnAbp.OrderingService.Domain.Shared/Localization/OrderingService/tr.json
- services/ordering/src/EShopOnAbp.OrderingService.Domain/Orders/OrderStatus.cs
Closes https://github.com/abpframework/abp/issues/11434
> eShopOnAbp: Refactor OrderStatus (remove unused states)

- services/administration/src/EShopOnAbp.AdministrationService.Application.Contracts/AdministrationServiceApplicationContractsModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.Application.Contracts/EShopOnAbp.AdministrationService.Application.Contracts.csproj
- services/administration/src/EShopOnAbp.AdministrationService.Application/AdministrationServiceApplicationModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.Application/EShopOnAbp.AdministrationService.Application.csproj
- services/administration/src/EShopOnAbp.AdministrationService.Domain.Shared/AdministrationServiceDomainSharedModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.Domain.Shared/EShopOnAbp.AdministrationService.Domain.Shared.csproj
- services/administration/src/EShopOnAbp.AdministrationService.Domain/AdministrationServiceDomainModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.Domain/EShopOnAbp.AdministrationService.Domain.csproj
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/EShopOnAbp.AdministrationService.EntityFrameworkCore.csproj
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/EntityFrameworkCore/AdministrationServiceDbContext.cs
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/EntityFrameworkCore/AdministrationServiceEntityFrameworkCoreModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/Migrations/20220220203632_Removed-FeatureManagement.Designer.cs
- services/administration/src/EShopOnAbp.AdministrationService.EntityFrameworkCore/Migrations/20220220203632_Removed-FeatureManagement.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Client/AdministrationServiceHttpApiClientModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Client/EShopOnAbp.AdministrationService.HttpApi.Client.csproj
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi/AdministrationServiceHttpApiModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi/EShopOnAbp.AdministrationService.HttpApi.csproj
Fixes https://github.com/abpframework/abp/issues/11637
> eShopOnAbp: Remove FeatureManagement

- services/catalog/src/EShopOnAbp.CatalogService.MongoDB/MongoDB/CatalogServiceMongoDbContext.cs
Used Products instead of Questions
> Corrected spelling mistake

- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/AdministrationServiceHttpApiHostModule.cs
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/DbMigrations/AdministrationServiceDatabaseMigrationChecker.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/DbMigrations/IdentityServiceDatabaseMigrationChecker.cs
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/IdentityServiceHttpApiHostModule.cs
- services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/OrderingServiceHttpApiHostModule.cs
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/PaymentServiceHttpApiHostModule.cs
- shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/EfCore/PendingEfCoreMigrationsChecker.cs
- shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/MongoDb/PendingMongoDbMigrationsChecker.cs
- shared/EShopOnAbp.Shared.Hosting.Microservices/DbMigrations/PendingMigrationsCheckerBase.cs
According to this problem: https://github.com/abpframework/eShopOnAbp/pull/90#pullrequestreview-912873088
> Retry logic for migrations

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Cart/Default.cshtml
> Show the image on the cart correctly

- apps/angular/src/environments/environment.ts
Closes https://github.com/abpframework/abp/issues/12097
> eShopOnAbp: Admin app should use SSO

- gateways/web-public/src/EShopOnAbp.WebPublicGateway/appsettings.Development.json
Fixes https://github.com/abpframework/abp/issues/12243
> EShopOnAbp.WebPublicGateway use same TCP ports of EShopOnAbp.CatalogService.HttpApi.Host

- apps/angular/projects/ordering/src/pages/orders/order-detail/order-detail.component.html
> Ddd abpLocalizationPipe  on order-detail.component.html

- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
- etc/docker/docker-compose.yml
- etc/docker/nginx/conf.d/default.conf
fixes https://github.com/abpframework/abp/issues/12917
> eShopOnAbp: SignalR error on k8s & docker-compose. Url re-write to https

- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
Resolves: https://github.com/abpframework/abp/issues/13360
> Application remote service configuration error

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/UserOrders/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Index.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/ProductDetail.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/ProductDetail.cshtml.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/index.css
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/components/user-orders/user-order-widget.css
closes https://github.com/abpframework/abp/issues/11428
> Product detail page

- build/build-images-locally.ps1
- build/build-images-locally.sh
- build/build-images.ps1
- build/build-images.sh
- build/publish-locally.ps1
- etc/README.md
- etc/k8s/azure/scripts/push-images.ps1
- etc/k8s/azure/scripts/push-images.sh
- etc/k8s/deploy-staging.sh
- etc/k8s/eshoponabp/charts/administration/templates/administration-ingress.yaml
- etc/k8s/eshoponabp/charts/authserver/templates/authserver-ingress.yaml
- etc/k8s/eshoponabp/charts/basket/templates/basket-ingress.yaml
- etc/k8s/eshoponabp/charts/catalog/templates/catalog-ingress.yaml
- etc/k8s/eshoponabp/charts/gateway-web-public/templates/gateway-web-public-ingress.yaml
- etc/k8s/eshoponabp/charts/gateway-web/templates/gateway-web-ingress.yaml
- etc/k8s/eshoponabp/charts/identity/templates/identity-ingress.yaml
- etc/k8s/eshoponabp/charts/ordering/templates/ordering-ingress.yaml
- etc/k8s/eshoponabp/charts/payment/templates/payment-ingress.yaml
- etc/k8s/eshoponabp/charts/public-web/templates/public-web-ingress.yaml
- etc/k8s/eshoponabp/charts/web/templates/web-configmap.yaml
- etc/k8s/eshoponabp/charts/web/templates/web-ingress.yaml
- etc/k8s/eshoponabp/values.azure.yaml
- etc/k8s/eshoponabp/values.yaml
close https://github.com/abpframework/abp/issues/12939
> eShopOnAbp:fix helm templates to use at local k8s and azure aks

- apps/auth-server/src/EShopOnAbp.AuthServer/appsettings.json
fixes https://github.com/volosoft/volo/issues/11030
> Updated password complexity

- services/ordering/src/EShopOnAbp.OrderingService.Application/Orders/OrderAppService.cs
fixes https://github.com/abpframework/abp/issues/13618
https://github.com/abpframework/eShopOnAbp/blob/80d61bd5054f01dfff36ea05c2623d8fb3b70e66/apps/public-web/src/EShopOnAbp.PublicWeb/Pages/OrderReceived.cshtml.cs#L21
> eshoponabp: gives 403 error at complete order step

- services/basket/src/EShopOnAbp.BasketService/BasketServiceModule.cs
- services/basket/src/EShopOnAbp.BasketService/EShopOnAbp.BasketService.csproj
fixes https://github.com/abpframework/abp/issues/13787
> Added retry mechanism

- services/ordering/src/EShopOnAbp.OrderingService.Application/Orders/OrderAppService.cs
- services/ordering/src/EShopOnAbp.OrderingService.Domain/Orders/IOrderRepository.cs
- services/ordering/src/EShopOnAbp.OrderingService.EntityFrameworkCore/Orders/EfCoreOrderRepository.cs
fixes https://github.com/abpframework/abp/issues/13805
> Eshop dashboard grouping issue 13805

- etc/docker/docker-compose.yml
docker-compose.yml  for   eshop-st-basket service   dockerfile path error
> fix: update docker-compose.yml for eshop-st-basket dockerfile path

- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/ProductDetail.cshtml.cs
fixes https://github.com/abpframework/abp/issues/14387
> Applied the temporary solution

- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
fixes https://github.com/abpframework/abp/issues/14420
> Removed domain dependency from web-public

- EShopOnAbp.sln
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Payment/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Menus/EShopOnAbpPublicWebMenus.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Basket.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Index.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/MyOrders.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/Payment.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/ProductDetail.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/productDetail.js
- apps/public-web/src/EShopOnAbp.PublicWeb/Themes/LeptonXLite/Components/Menu/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/global.css
closes https://github.com/abpframework/eShopOnAbp/issues/155
> Leptonx theme changes

- apps/angular/src/app/app.module.ts
- apps/public-web/src/EShopOnAbp.PublicWeb/Menus/EShopOnAbpPublicWebMenuContributor.cs
Related to https://github.com/abpframework/eShopOnAbp/issues/176
If @mahmut-gundogdu or @masumulu28 can help, need a fix for admin (angular app) aswell.
> Manage account link fix

- .env.example
Fixes https://github.com/abpframework/eShopOnAbp/issues/182
File was deleted mistakenly with https://github.com/abpframework/eShopOnAbp/pull/180/commits/2600b6bf0808ba212615b5a25ab7ed228113bf6d
> .env.example file does not exist

- shared/EShopOnAbp.Shared.Hosting.Gateways/EShopOnAbp.Shared.Hosting.Gateways.csproj
[Microsoft Security Advisory CVE-2023-33141 | YARP Denial of Service Vulnerability](https://github.com/microsoft/reverse-proxy/security/advisories/GHSA-jrjw-qgr2-wfcg)
> Yarp security update

- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/DbMigrations/AdministrationServiceDataSeedContributor.cs
Closes https://github.com/abpframework/eShopOnAbp/issues/191
Workaround fix to https://github.com/abpframework/eShopOnAbp/issues/197 for deployment.;
> Added permission seeding for client credentials flow

- apps/angular/angular.json
- apps/angular/src/environments/environment.ts
fixes https://github.com/abpframework/eShopOnAbp/issues/200
> Back-office application unsupported mime type error

- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbp.PublicWeb.csproj
Forgotten in https://github.com/abpframework/eShopOnAbp/pull/190
> Yarp security update for public-web app

- build/build-images-locally.ps1
- build/build-images-locally.sh
- build/build-images.ps1
- build/build-images.sh
- build/publish-locally.ps1
Added missing updates from https://github.com/abpframework/eShopOnAbp/pull/227
> Updated default image build scripts

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Footer/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Footer/FooterComponent.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/EShopOnAbpPublicWebModule.cs
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/_ViewStart.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Pages/index.css
- apps/public-web/src/EShopOnAbp.PublicWeb/wwwroot/global.css
> Add demo website GitHub link to the footer

- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Footer/Default.cshtml
- apps/public-web/src/EShopOnAbp.PublicWeb/Components/Toolbar/Footer/FooterComponent.cs
> Footer enhancement

- apps/angular/Dockerfile.azure
- apps/public-web/src/EShopOnAbp.PublicWeb/Dockerfile.azure
- etc/k8s/azure/azure-pipelines.yml
- gateways/web-public/src/EShopOnAbp.WebPublicGateway/Dockerfile.azure
- gateways/web/src/EShopOnAbp.WebGateway/Dockerfile.azure
- services/administration/src/EShopOnAbp.AdministrationService.HttpApi.Host/Dockerfile.azure
- services/basket/src/EShopOnAbp.BasketService/Dockerfile.azure
- services/catalog/src/EShopOnAbp.CatalogService.HttpApi.Host/Dockerfile.azure
- services/cmskit/src/EShopOnAbp.CmskitService.HttpApi.Host/Dockerfile.azure
- services/identity/src/EShopOnAbp.IdentityService.HttpApi.Host/Dockerfile.azure
- services/ordering/src/EShopOnAbp.OrderingService.HttpApi.Host/Dockerfile.azure
- services/payment/src/EShopOnAbp.PaymentService.HttpApi.Host/Dockerfile.azure
Resolves https://github.com/volosoft/vs-internal/issues/4229
> Created new docker files and pipelines for azure kubernetes deployment 

- services/identity/src/EShopOnAbp.IdentityService.Application/UserLoggedInEventHandler.cs
Fixes https://github.com/abpframework/eShopOnAbp/issues/242
> Admin user sync problem
